<Project Sdk="Aspire.AppHost.Sdk/13.1.0">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>359c2a7c-5075-4843-a62a-be61fc0c01d7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\backend\OpenFlat.Cleaning.Api\OpenFlat.Cleaning.Api.csproj" />
    <ProjectReference Include="..\backend\OpenFlat.Shopping.Api\OpenFlat.Shopping.Api.csproj" />
    <ProjectReference Include="..\backend\OpenFlat.Finance.Api\OpenFlat.Finance.Api.csproj" />
    <ProjectReference Include="..\OpenFlat.MigrationService\OpenFlat.MigrationService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.1.0" />
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.1.0" />
  </ItemGroup>
</Project>
