// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenFlat.Api.Features.Cleaning.Data;

#nullable disable

namespace OpenFlat.Api.Features.Cleaning.Data.Migrations
{
    [DbContext(typeof(CleaningDbContext))]
    [Migration("20260309214441_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cleaning")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenFlat.Api.Features.Cleaning.Data.CleaningComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_cleaning_comments_task_id");

                    b.HasIndex("TaskId", "CreatedAt")
                        .HasDatabaseName("ix_cleaning_comments_task_created");

                    b.ToTable("comments", "cleaning");
                });

            modelBuilder.Entity("OpenFlat.Api.Features.Cleaning.Data.CleaningCompletionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CompletedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompletedByUserId")
                        .HasDatabaseName("ix_completion_log_completed_by");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_completion_log_task_id");

                    b.ToTable("completion_log", "cleaning");
                });

            modelBuilder.Entity("OpenFlat.Api.Features.Cleaning.Data.CleaningTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("Effort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("FrequencyUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("FrequencyValue")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastCompletedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("RotationIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.PrimitiveCollection<int[]>("RotationOrder")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer[]")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId")
                        .HasDatabaseName("ix_tasks_assigned_user_id")
                        .HasFilter("\"AssignedUserId\" IS NOT NULL");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_tasks_due_date");

                    b.ToTable("tasks", "cleaning");
                });

            modelBuilder.Entity("OpenFlat.Api.Features.Cleaning.Data.CleaningComment", b =>
                {
                    b.HasOne("OpenFlat.Api.Features.Cleaning.Data.CleaningTask", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("OpenFlat.Api.Features.Cleaning.Data.CleaningCompletionLog", b =>
                {
                    b.HasOne("OpenFlat.Api.Features.Cleaning.Data.CleaningTask", "Task")
                        .WithMany("CompletionLogs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("OpenFlat.Api.Features.Cleaning.Data.CleaningTask", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("CompletionLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
